apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
  labels:
    app.kubernetes.io/instance: churn-mlops
spec:
  predictor:
    serviceAccountName: sa-az-access
    containers:
      - name: kserve-container
        image: churn-kserve:latest
        args:
          - "--model_name=churn-predictor"
          - "--model_dir=/mnt/models"
          - "--model_file=churn_model.pkl"
        volumeMounts:
          - name: kserve-provision-location
            mountPath: /mnt/models
            readOnly: true
    initContainers:
      - name: storage-initializer
        image: docker.io/kserve/storage-initializer:v0.11.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Persistent fix: Dynamically append SAS token from secret to URI
            MODEL_URI="https://storageaccountmlopspoc.blob.core.windows.net/models-container/models/e9473be2e5b8a903fdcfe90ba74de3f0a509c581/"
            /storage-initializer/scripts/initializer-entrypoint "${MODEL_URI}?${AZURE_STORAGE_SAS_TOKEN}" /mnt/models
        env:
          - name: AZURE_STORAGE_SAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: az-secret
                key: AZURE_STORAGE_SAS_TOKEN
        volumeMounts:
          - name: kserve-provision-location
            mountPath: /mnt/models
    volumes:
      - name: kserve-provision-location
        emptyDir: {}
