apiVersion: v1
kind: Namespace
metadata:
  name: churn-model
---
apiVersion: v1
kind: Secret
metadata:
  name: az-secret
  namespace: churn-model
  annotations:
    argocd.argoproj.io/sync-options: Skip=true
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "<YOUR_AZURE_ACCESS_TOKEN_HERE>"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-az-access
  namespace: churn-model
secrets:
  - name: az-secret
